version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./images:/app/images
    # İsterseniz, environment değişkenlerini de ekleyebilirsiniz.
    # environment:
    #   - FLASK_ENV=development
