version: "3.8"

services:
  app:
    build: .
    ports:
      - "5031:5031"
      - "8502:8502"
    volumes:
      - ./images:/app/images
    environment:
      # These will be picked up from Coolify’s Environment Variables:
      LLM_API_KEY:     "${LLM_API_KEY}"
      PLANNER_API_KEY: "${PLANNER_API_KEY}"
      OPENAI_API_KEY:  "${OPENAI_API_KEY}"
